[package]
name = "hurl"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
heck = "0.3"
serde = "1.0"
reqwest = "0.9.20"
serde_json = "1.0"
structopt = "0.3"
rpassword = "4.0"
