[package]
name = "messages-actix"
version = "0.1.0"
authors = ["Your Name <your.name@example.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
