[package]
name = "sudoku"
version = "0.1.0"
authors = ["Andrew Weiss <wvvwwvw@gmail.com>"]
edition = "2018"

[[bin]]
name = "sudoku-cli"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen="^0.2"
